name: tasker
description: A task management app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.1
  google_sign_in: ^5.4.4
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
